name: Release
on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
      - 'cli/**'
      - 'runtime/**'
      - 'yarn.lock'
    branches:
      - 'master'

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI: true

jobs:
  Release:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      packages: write
      contents: write

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: styfle/cancel-workflow-action@0.12.0
        with:
          workflow_id: release.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          fetch-depth: 30

      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Yarn
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          yarn install --frozen-lockfile --ignore-scripts
          yarn buildall
          yarn test

      - name: Build and Test Demo APP
        run: |
          ./demo-apps/build-and-test.sh

      - name: Release
        run: |
          npm i -g semantic-release @semantic-release/git @semantic-release/github conventional-changelog-conventionalcommits @semantic-release/exec
          semantic-release --no-ci --debug
          ./publish.sh master
